name = "blog-website"
skipFolders = [ "node_modules", ".vscode", "out", "dist", ".vscode-test" ]
skipFiles = [ ".gitignore", "package.json" ]

[[processes]]
id = "process1"
name = "To Do"

  [[processes.tasks]]
  id = "nj7q1zsy7aryozmpzo9g22rx"
  title = "Color Pallet"
  description = "<p>Generate a nice dark themed color pallet from https://www.realtimecolors.com</p>"
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = "Low"
  linkCommits = [ ]

  [[processes.tasks]]
  id = "xb55gmw07lp5f2sgsmgsn40k"
  title = "Generate Dynamic Metadata"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

[[processes]]
id = "process2"
name = "In Progress"

  [[processes.tasks]]
  id = "tsdz4zetkou98vcnbjtwaokw"
  title = "Create all Routes"
  description = "<p></p>"
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = "High"
  linkCommits = [ ]

  [[processes.tasks]]
  id = "pt5sxuc48l218czamkqm32cp"
  title = "Search bar"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

[[processes]]
id = "process3"
name = "Done"

  [[processes.tasks]]
  id = "eurah18yepq96cz9hhza9iwf"
  title = "Add Clerk"
  description = "<p>Clerk Authentication</p>"
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = "High"
  linkCommits = [ ]

  [[processes.tasks]]
  id = "q5tyiqqvuv81yjmdo2jtiieu"
  title = "Create Database"
  description = "<p>Create database using Prisma</p>"
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = "High"
  linkCommits = [ ]
